### ISSUE TITLE
headerview也带上分割线了怎么办

### ISSUE THREAD

**Issue by zhaoziliang01** [happyjosh/XXXRecyclerViewDivider#1]

**Comment by happyjosh** [comment]
可复写isAllowShowDivider()，来控制对应的item是否显示分割

**Comment by zhaoziliang01** [comment]
可否具体写出来呢？我没找到判断headerview的方法。。。

**Comment by happyjosh** [comment]
`public class LightFloorDivider extends LinearItemDecoration {
    public LightFloorDivider(Context context) {
        super(context, R.color.post_line_color, R.dimen.divider_height);
    }

    @Override
    protected boolean isAllowShowDivider(int position, RecyclerView parent) {
        RecyclerView.Adapter adapter = parent.getAdapter();
        if (adapter.getItemViewType(position) == FloorRecyclerAdapter.ITEM_TYPE_TITLE) {
            //Title对应item下方不显示分割
            return false;
        }
        if (position < adapter.getItemCount() - 1 &&
                parent.getAdapter().getItemViewType(position + 1) == FloorRecyclerAdapter.ITEM_TYPE_TITLE) {
            //Title对应上方不显示分割
            return false;
        }
        return super.isAllowShowDivider(position, parent);
    }
}`
类似以上代码，你肯定能够判断是否是headerView，如果是headerView就return false。

**Comment by zhaoziliang01** [comment]
private boolean isInFirstGroup(int position, RecyclerView parent) {
        int spanCount = getSpanCount(parent);
        GridLayoutManager gridLayoutManager = (GridLayoutManager) parent.getLayoutManager();
        GridLayoutManager.SpanSizeLookup spanSizeLookup = gridLayoutManager.getSpanSizeLookup();
        return spanSizeLookup.getSpanGroupIndex(0, spanCount)
                == spanSizeLookup.getSpanGroupIndex(position, spanCount);
    }





    /**
     * 子类可控制是否显示分割
     *
     * @param position
     * @param parent
     * @return
     */
    protected boolean isAllowShowDivider(int position, RecyclerView parent) {
        if (isInLastGroup(position, parent)) {
            //末尾不显示分割
            return false;
        }

        if (isShowHeader && isInFirstGroup(position, parent)) {
            //末尾不显示分割
            return false;
        }
        return true;
    }
我这样加了个判断也能实现效果。。。

**Comment by zhaoziliang01** [comment]
private boolean isShowHeader=false;
    public GridItemDecoration(Context context,boolean isShowTopHeaderFlag, @DrawableRes int drawRes,
                              @DimenRes int dividerWidthRes, @DimenRes int dividerHeightRes) {
        this(ContextCompat.getDrawable(context, drawRes), context.getResources().
                getDimensionPixelSize(dividerWidthRes), context.getResources().
                getDimensionPixelSize(dividerHeightRes));
        this.isShowHeader=isShowTopHeaderFlag;
    }

加了个标志位

**Comment by happyjosh** [comment]
不是很了解你的具体业务逻辑，解决了就好[抱拳]。总之isAllowShowDivider方法就是用来做自定义控制每个Item是否显示分割线的，在里面加上自己需要的对应判断就好了。

**Comment by zhaoziliang01** [comment]
好的谢谢作者老铁
